In [33]:
import torch
from torchmetrics import Specificity, F1Score, Accuracy
preds  = torch.tensor([2, 0, 2,2,2, 1])
target = torch.tensor([1, 1, 2,2,2, 0])
# specificity = Specificity(average='macro', num_classes=3)
f1 = F1Score(average='macro',num_classes=3)
acc = Accuracy(average='macro',num_classes=3)
specificity(preds, target)

specificity = Specificity(average='macro', num_classes=3)
specificity(preds, target)

tensor(0.7389)

In [25]:
f1(preds, target)

tensor(0.2857)

In [28]:
acc(preds, target)

tensor(0.3333)

In [23]:
from sklearn.metrics import f1_score
f1 = f1_score(target, preds, average='macro')
f1

0.2857142857142857

In [26]:
(0.75)/3

0.25

In [39]:
import torch
from  torchmetrics.functional import retrieval_recall
preds = torch.tensor([0.2, 0.3, 0.5])
target = torch.tensor([True, False, True])
# preds  = torch.tensor([2, 0, 2,2,2, 1])
# target = torch.tensor([1, 1, 2,2,2, 0])
retrieval_recall(preds, target, k=2)


tensor(0.5000)

In [43]:
from sklearn.metrics import recall_score
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
preds  = torch.tensor([2, 0, 2,2,2, 1])
target = torch.tensor([1, 1, 2,2,2, 0])
print(recall_score(y_true, y_pred, average='macro'))
print(recall_score(y_true, y_pred, average='micro'))
print(recall_score(y_true, y_pred, average='weighted'))

0.3333333333333333
0.3333333333333333
0.3333333333333333


In [ ]:

>>> recall_score(y_true, y_pred, average='micro')
0.33...
>>> recall_score(y_true, y_pred, average='weighted')
0.33...
>>> recall_score(y_true, y_pred, average=None)
array([1., 0., 0.])
>>> y_true = [0, 0, 0, 0, 0, 0]
>>> recall_score(y_true, y_pred, average=None)
array([0.5, 0. , 0. ])
>>> recall_score(y_true, y_pred, average=None, zero_division=1)
array([0.5, 1. , 1. ])
>>> # multilabel classification
>>> y_true = [[0, 0, 0], [1, 1, 1], [0, 1, 1]]
>>> y_pred = [[0, 0, 0], [1, 1, 1], [1, 1, 0]]
>>> recall_score(y_true, y_pred, average=None)
array([1. , 1. , 0.5])